# Generated by Django 2.1.7 on 2021-07-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='board',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
