# Generated by Django 2.1.7 on 2021-08-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', utils.models.RichTextField()),
                ('subject', models.TextField()),
                ('purpose', models.TextField()),
                ('schedule', models.TextField()),
                ('curriculum', models.TextField()),
                ('max_students', models.IntegerField()),
                ('reason', models.TextField()),
                ('notice', models.TextField()),
                ('status', models.TextField()),
                ('price', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='learning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='StudyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'study_tag',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='tags',
            field=models.ManyToManyField(to='study.StudyTag'),
        ),
    ]
