# Generated by Django 2.1.7 on 2021-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_workers', models.IntegerField(default=0)),
                ('salary_man', models.IntegerField(default=0)),
            ],
        ),
    ]
